version: '3.7'

services:
  app:
    build:
      args:
        user: seguro
        uid: 1001
      context: ./app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: plataformaPS
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: prograSegura2024_8
    ports:
      - "3306:3306"
    command: --bind-address=0.0.0.0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "1024M"

  nginx:
    image: nginx
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/certs:/tmp
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/proyectoPrograSegura/static:/static
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "1024M"

