# Generated by Django 4.2.11 on 2024-04-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Intentos",
            fields=[
                ("ip", models.GenericIPAddressField(primary_key=True, serialize=False)),
                ("intentos", models.PositiveIntegerField()),
                ("fecha_ultimo_intento", models.DateTimeField()),
            ],
        ),
    ]
