# Generated by Django 4.2.11 on 2024-05-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intentos',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('intentos', models.PositiveIntegerField()),
                ('fecha_ultimo_intento', models.DateTimeField()),
            ],
        ),
    ]
