# Generated by Django 4.2.11 on 2024-05-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0002_intentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenOcupados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=18)),
                ('tiempo', models.DateField(auto_now_add=True)),
                ('estatus', models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')])),
            ],
        ),
    ]
