# Generated by Django 4.2.11 on 2024-05-06 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0002_alumno_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='alumno',
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
