# Generated by Django 4.2.11 on 2024-05-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0007_validatoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramToken',
            fields=[
                ('id_token', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_telegram', models.CharField(max_length=20)),
                ('nombre_usuario', models.CharField(max_length=20)),
                ('tokens', models.CharField(max_length=6)),
                ('tiempo', models.TimeField()),
                ('estatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='validaToken',
        ),
    ]
