# Generated by Django 4.2.11 on 2024-05-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0012_remove_telegramdata_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramdata',
            name='usuarioTelegram',
            field=models.CharField(max_length=40),
        ),
    ]
