# Generated by Django 4.2.11 on 2024-06-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0013_alter_telegramdata_usuariotelegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_Maestro',
            fields=[
                ('idRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=20)),
                ('contrasenia', models.BinaryField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='TokenOcupados',
        ),
    ]
