# Generated by Django 4.2.11 on 2024-06-07 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0014_usuario_maestro_delete_tokenocupados'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario_Maestro',
        ),
    ]
