# Generated by Django 4.2.11 on 2024-05-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0003_tokenocupados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenocupados',
            name='tiempo',
            field=models.TimeField(),
        ),
    ]
