# Generated by Django 4.2.11 on 2024-05-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0004_alter_tokenocupados_tiempo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenDeAutenticacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.TimeField()),
                ('estatus', models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')])),
            ],
        ),
        migrations.RemoveField(
            model_name='tokenocupados',
            name='estatus',
        ),
        migrations.RemoveField(
            model_name='tokenocupados',
            name='tiempo',
        ),
    ]
