# Generated by Django 4.2.11 on 2024-05-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0005_tokendeautenticacion_remove_tokenocupados_estatus_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenDeAutenticacion',
        ),
        migrations.AlterField(
            model_name='tokenocupados',
            name='token',
            field=models.CharField(max_length=32),
        ),
    ]
