# Generated by Django 4.2.11 on 2024-05-23 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0008_telegramtoken_delete_validatoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramtoken',
            name='nombre_usuario',
        ),
    ]
