# Generated by Django 4.2.11 on 2024-05-23 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0009_remove_telegramtoken_nombre_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelegramToken',
            new_name='TelegramData',
        ),
        migrations.RenameField(
            model_name='telegramdata',
            old_name='usuario_telegram',
            new_name='usuario',
        ),
    ]
