# Generated by Django 4.2.11 on 2024-05-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0010_rename_telegramtoken_telegramdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramdata',
            name='chat_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='telegramdata',
            name='enviar',
            field=models.BooleanField(default=True),
        ),
    ]
