# Generated by Django 4.2.11 on 2024-05-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0011_telegramdata_chat_id_telegramdata_enviar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramdata',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='telegramdata',
            name='estatus',
        ),
        migrations.AddField(
            model_name='telegramdata',
            name='usuarioTelegram',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
