# Generated by Django 4.2.11 on 2024-06-07 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0015_delete_usuario_maestro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bd.alumno'),
        ),
    ]
